
// This file has been generated by the GUI designer. Do not modify.
namespace ComboBoxBinding
{
	public partial class MainWindow
	{
		private global::Gtk.Notebook notebook1;

		private global::Gtk.HBox hbox1;

		private global::GtkForms.FormsLabel formslabel1;

		private global::GtkForms.FormsComboBox formscombobox1;

		private global::Gtk.Button button1;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox2;

		private global::GtkForms.FormsLabel formslabel2;

		private global::GtkForms.FormsComboBox formscombobox2;

		private global::Gtk.Button button2;

		private global::Gtk.Button button5;

		private global::Gtk.Label label2;

		private global::Gtk.HBox hbox3;

		private global::GtkForms.FormsLabel formslabel4;

		private global::GtkForms.FormsLabel formslabel3;

		private global::GtkForms.FormsComboBoxEntry formscomboboxentry1;

		private global::Gtk.Button button3;

		private global::Gtk.Button button4;

		private global::Gtk.Label label3;

		private global::Gtk.HBox hbox4;

		private global::GtkForms.FormsLabel labelCityName;

		private global::GtkForms.FormsComboBox formscombobox3;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ComboBoxBinding.MainWindow
			this.Name = "ComboBoxBinding.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("ComboBox binding");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ComboBoxBinding.MainWindow.Gtk.Container+ContainerChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 3;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.formslabel1 = new global::GtkForms.FormsLabel ();
			this.formslabel1.Name = "formslabel1";
			this.hbox1.Add (this.formslabel1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.formslabel1]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.formscombobox1 = new global::GtkForms.FormsComboBox ();
			this.formscombobox1.Name = "formscombobox1";
			this.hbox1.Add (this.formscombobox1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.formscombobox1]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.Sensitive = false;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
			this.hbox1.Add (this.button1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.notebook1.Add (this.hbox1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("List");
			this.notebook1.SetTabLabel (this.hbox1, this.label1);
			this.label1.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.formslabel2 = new global::GtkForms.FormsLabel ();
			this.formslabel2.Name = "formslabel2";
			this.hbox2.Add (this.formslabel2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.formslabel2]));
			w5.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.formscombobox2 = new global::GtkForms.FormsComboBox ();
			this.formscombobox2.Name = "formscombobox2";
			this.hbox2.Add (this.formscombobox2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.formscombobox2]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Change first item");
			this.hbox2.Add (this.button2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button2]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString ("Set position");
			this.hbox2.Add (this.button5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button5]));
			w8.Position = 3;
			w8.Expand = false;
			w8.Fill = false;
			this.notebook1.Add (this.hbox2);
			global::Gtk.Notebook.NotebookChild w9 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox2]));
			w9.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("BindingSource");
			this.notebook1.SetTabLabel (this.hbox2, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.formslabel4 = new global::GtkForms.FormsLabel ();
			this.formslabel4.Name = "formslabel4";
			this.hbox3.Add (this.formslabel4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.formslabel4]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.formslabel3 = new global::GtkForms.FormsLabel ();
			this.formslabel3.Name = "formslabel3";
			this.hbox3.Add (this.formslabel3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.formslabel3]));
			w11.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.formscomboboxentry1 = new global::GtkForms.FormsComboBoxEntry ();
			this.formscomboboxentry1.Name = "formscomboboxentry1";
			this.hbox3.Add (this.formscomboboxentry1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.formscomboboxentry1]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button ();
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString ("Change first item");
			this.hbox3.Add (this.button3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button3]));
			w13.Position = 3;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button ();
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString ("Clear");
			this.hbox3.Add (this.button4);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.button4]));
			w14.Position = 4;
			w14.Expand = false;
			w14.Fill = false;
			this.notebook1.Add (this.hbox3);
			global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox3]));
			w15.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("BindingList");
			this.notebook1.SetTabLabel (this.hbox3, this.label3);
			this.label3.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelCityName = new global::GtkForms.FormsLabel ();
			this.labelCityName.Name = "labelCityName";
			this.hbox4.Add (this.labelCityName);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.labelCityName]));
			w16.Position = 0;
			w16.Expand = false;
			w16.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.formscombobox3 = new global::GtkForms.FormsComboBox ();
			this.formscombobox3.Name = "formscombobox3";
			this.hbox4.Add (this.formscombobox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.formscombobox3]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.notebook1.Add (this.hbox4);
			global::Gtk.Notebook.NotebookChild w18 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox4]));
			w18.Position = 3;
			w18.MenuLabel = global::Mono.Unix.Catalog.GetString ("Null value");
			this.Add (this.notebook1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 408;
			this.DefaultHeight = 98;
			this.button1.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.button1.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
			this.button2.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
			this.button5.Clicked += new global::System.EventHandler (this.OnButton5Clicked);
			this.button3.Clicked += new global::System.EventHandler (this.OnButton3Clicked);
			this.button4.Clicked += new global::System.EventHandler (this.OnButton4Clicked);
		}
	}
}
