
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.HBox hbox1;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::GtkForms.FormsGridView gridview;

	private global::Gtk.Table table1;

	private global::Gtk.Alignment alignmentFavourite;

	private global::GtkForms.FormsCheckButton checkFavourite;

	private global::Gtk.Alignment alignmentPrice;

	private global::GtkForms.FormsSpinButton spinPrice;

	private global::GtkForms.FormsEntry entryID;

	private global::GtkForms.FormsEntry entryName;

	private global::Gtk.Label labelError;

	private global::GtkForms.FormsLabel labelFavourite;

	private global::GtkForms.FormsLabel labelID;

	private global::GtkForms.FormsLabel labelName;

	private global::GtkForms.FormsLabel labelPrice;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.gridview = new global::GtkForms.FormsGridView ();
		this.gridview.CanFocus = true;
		this.gridview.Name = "gridview";
		this.gridview.AutoGenerateColumns = true;
		this.GtkScrolledWindow.Add (this.gridview);
		this.hbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		this.table1.BorderWidth = ((uint)(4));
		// Container child table1.Gtk.Table+TableChild
		this.alignmentFavourite = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
		this.alignmentFavourite.Name = "alignmentFavourite";
		// Container child alignmentFavourite.Gtk.Container+ContainerChild
		this.checkFavourite = new global::GtkForms.FormsCheckButton ();
		this.checkFavourite.CanFocus = true;
		this.checkFavourite.Name = "checkFavourite";
		this.checkFavourite.Label = "";
		this.checkFavourite.DrawIndicator = true;
		this.alignmentFavourite.Add (this.checkFavourite);
		this.table1.Add (this.alignmentFavourite);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.alignmentFavourite]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.alignmentPrice = new global::Gtk.Alignment (0.01f, 0.5f, 0f, 1f);
		this.alignmentPrice.Name = "alignmentPrice";
		// Container child alignmentPrice.Gtk.Container+ContainerChild
		this.spinPrice = new global::GtkForms.FormsSpinButton ();
		this.spinPrice.WidthRequest = 60;
		this.spinPrice.CanFocus = true;
		this.spinPrice.Name = "spinPrice";
		this.alignmentPrice.Add (this.spinPrice);
		this.table1.Add (this.alignmentPrice);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.alignmentPrice]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.LeftAttach = ((uint)(1));
		w6.RightAttach = ((uint)(2));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryID = new global::GtkForms.FormsEntry ();
		this.entryID.CanFocus = true;
		this.entryID.Name = "entryID";
		this.entryID.IsEditable = true;
		this.entryID.InvisibleChar = '●';
		this.table1.Add (this.entryID);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.entryID]));
		w7.LeftAttach = ((uint)(1));
		w7.RightAttach = ((uint)(2));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.entryName = new global::GtkForms.FormsEntry ();
		this.entryName.CanFocus = true;
		this.entryName.Name = "entryName";
		this.entryName.IsEditable = true;
		this.entryName.InvisibleChar = '●';
		this.table1.Add (this.entryName);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.entryName]));
		w8.TopAttach = ((uint)(1));
		w8.BottomAttach = ((uint)(2));
		w8.LeftAttach = ((uint)(1));
		w8.RightAttach = ((uint)(2));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelError = new global::Gtk.Label ();
		this.labelError.Name = "labelError";
		this.labelError.LabelProp = global::Mono.Unix.Catalog.GetString ("error message");
		this.table1.Add (this.labelError);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.labelError]));
		w9.TopAttach = ((uint)(4));
		w9.BottomAttach = ((uint)(5));
		w9.RightAttach = ((uint)(3));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelFavourite = new global::GtkForms.FormsLabel ();
		this.labelFavourite.Name = "labelFavourite";
		this.labelFavourite.Xalign = 1f;
		this.labelFavourite.Yalign = 0f;
		this.labelFavourite.LabelProp = global::Mono.Unix.Catalog.GetString ("Favourite");
		this.table1.Add (this.labelFavourite);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.labelFavourite]));
		w10.TopAttach = ((uint)(3));
		w10.BottomAttach = ((uint)(4));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelID = new global::GtkForms.FormsLabel ();
		this.labelID.Name = "labelID";
		this.labelID.Xalign = 1f;
		this.labelID.Yalign = 0f;
		this.labelID.LabelProp = global::Mono.Unix.Catalog.GetString ("ID");
		this.table1.Add (this.labelID);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.labelID]));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelName = new global::GtkForms.FormsLabel ();
		this.labelName.Name = "labelName";
		this.labelName.Xalign = 1f;
		this.labelName.Yalign = 0f;
		this.labelName.LabelProp = global::Mono.Unix.Catalog.GetString ("Company name\n");
		this.table1.Add (this.labelName);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.labelName]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.labelPrice = new global::GtkForms.FormsLabel ();
		this.labelPrice.Name = "labelPrice";
		this.labelPrice.Xalign = 1f;
		this.labelPrice.Yalign = 0f;
		this.labelPrice.LabelProp = global::Mono.Unix.Catalog.GetString ("Price");
		this.table1.Add (this.labelPrice);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.labelPrice]));
		w13.TopAttach = ((uint)(2));
		w13.BottomAttach = ((uint)(3));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox1.Add (this.table1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.table1]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		this.Add (this.hbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 452;
		this.DefaultHeight = 300;
		this.labelError.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.entryName.Validating += new global::System.ComponentModel.CancelEventHandler (this.OnEntryNameValidating);
	}
}
