// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// This file has been generated by the GUI designer. Do not modify.


public partial class MainWindow
{

	private global::Gtk.HBox hbox;

	private global::GtkForms.FormsLabel label;

	private global::GtkForms.FormsDatePicker datepicker;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("DatePicker demo");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.hbox = new global::Gtk.HBox ();
		this.hbox.Name = "hbox";
		this.hbox.Spacing = 6;
		// Container child hbox.Gtk.Box+BoxChild
		this.label = new global::GtkForms.FormsLabel ();
		this.label.Name = "label";
		this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("formslabel1");
		this.hbox.Add (this.label);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox[this.label]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox.Gtk.Box+BoxChild
		this.datepicker = new global::GtkForms.FormsDatePicker ();
		this.datepicker.Events = ((global::Gdk.EventMask)(256));
		this.datepicker.Name = "datepicker";
		this.hbox.Add (this.datepicker);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox[this.datepicker]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.Add (this.hbox);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 387;
		this.DefaultHeight = 49;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
