// 
//  DataGridViewDecorator.cs
//  
//  Author:
//       Krzysztof Marecki 
// 
//	Copyright (c) 2010 Krzysztof Marecki 
//
//  This library is free software; you can redistribute it and/or modify
//  it under the terms of the GNU Lesser General Public License as
//  published by the Free Software Foundation; either version 2.1 of the
//  License, or (at your option) any later version.
// 
//  This library is distributed in the hope that it will be useful, but
//  WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
//  Lesser General Public License for more details.
// 
//  You should have received a copy of the GNU Lesser General Public
//  License along with this library; if not, write to the Free Software
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;
using Gtk;

namespace GtkForms
{

	public class GridViewDecorator <T> : BaseListWidgetDecorator<T>
		where T : TreeView, IDecoratedGridView
	{
		private T grid;
		private Dictionary<TreeViewColumn, PropertyDescriptor> treecolumns;
		private List <ListSortDescription> sorts;
		
		private bool auto_generate_columns = true;
		public bool AutoGenerateColumns {
			get { return auto_generate_columns; }
			set { auto_generate_columns = value; }
		}
		
		public List<GridViewColumn> Columns { get; private set; }

		public GridViewDecorator (T widget)
			: base (widget)
		{
			grid = widget;
			sorts = new List<ListSortDescription> ();
			Columns = new List<GridViewColumn> ();
		}
		
		protected override ListStore CreateStore ()
		{
			ListStore store = null;
			var types = new List<Type>();
			
			foreach (var col in Columns) {
				PropertyDescriptor prop = col.DataProperty;
				if (prop != null) {
					types.Add (typeof (string));
				}
			}
			
			store = new ListStore (types.ToArray ());
			return store;
		}
		
		protected override void SetCellRenderers ()
		{
			treecolumns = new Dictionary<TreeViewColumn, PropertyDescriptor> ();
			
			if (AutoGenerateColumns) {
				CreateAutoGeneratedColumns ();
			}
			FindPropertyDescriptors ();
			
			int count = 0;
			foreach (var col in Columns) {
				PropertyDescriptor prop = col.DataProperty;
				if (prop != null) {
					CellRendererText ct = new CellRendererText ();
					ct.Editable = col.ReadOnly;
					
					SetCellRendererAlignment (ct, col);
					
					var treecol = new TreeViewColumn (col.HeaderText, ct, "text", count++);
					if (col.Width > 0) {
						treecol.MinWidth = col.Width;
					}
					treecol.Clickable = grid.HeadersClickable;
					treecol.Clicked += HandleTreeColumnClicked;
					
					grid.AppendColumn (treecol);
					treecolumns.Add (treecol, prop);
				}
			}
		}
		
		protected override void RefreshDataSource ()
		{
			Sort ();
			base.RefreshDataSource ();
		}
		
		protected override object[] GetItemValues (object item)
		{
			var values = new List<object> ();
			
			foreach (var col in Columns) {
				PropertyDescriptor prop = col.DataProperty;
				if (prop != null) {
					object propval = prop.GetValue (item);
					string format = !string.IsNullOrEmpty (col.DefaultCellStyle.Format)
						? string.Format ("{{0:{0}}}", col.DefaultCellStyle.Format)
						: "{0}";
					string val = (propval != null) 
						? string.Format (format, propval) 
						: string.Empty;
					values.Add (val);
				}
			}
			
			return values.ToArray ();
		}
		
		void CreateAutoGeneratedColumns ()
		{
			foreach (PropertyDescriptor prop in DataManager.GetItemProperties ()) {
				var col = new GridViewColumn ();
				col.DataPropertyName = prop.Name;
				col.Name = string.Format ("col{0}", prop.Name);
				col.HeaderText = prop.DisplayName;
				col.ReadOnly = true;
				Columns.Add (col);
			}
		}
		
		void FindPropertyDescriptors ()
		{
			foreach (var col in Columns) {
				var prop = DataManager.GetItemProperties ()
					.OfType<PropertyDescriptor> ()
						.FirstOrDefault (p => col.DataPropertyName == p.Name);
				col.DataProperty = prop;
			}
		}
		
		void SetCellRendererAlignment (CellRendererText ct, GridViewColumn col)
		{
			switch (col.DefaultCellStyle.Alignment) {
				case GridViewContentAlignment.BottomCenter : {
					ct.Xalign = 0.5f;
					ct.Yalign = 1f;
					break;
				}
				case GridViewContentAlignment.BottomLeft : {
					ct.Xalign = 0f;
					ct.Yalign = 1f;
					break;
				}
				case GridViewContentAlignment.BottomRight : {
					ct.Xalign = 1f;
					ct.Yalign = 1f;
					break;
				}
				case GridViewContentAlignment.MiddleCenter : {
					ct.Xalign = 0.5f;
					ct.Yalign = 0.5f;
					break;
				}
				case GridViewContentAlignment.MiddleLeft : {
					ct.Xalign = 0f;
					ct.Yalign = 0.5f;
					break;
				}
				case GridViewContentAlignment.MiddleRight : {
					ct.Xalign = 1f;
					ct.Yalign = 0.5f;
					break;
				}
				case GridViewContentAlignment.TopCenter : {
					ct.Xalign = 0.5f;
					ct.Yalign = 0f;
					break;
				}
				case GridViewContentAlignment.TopLeft : {
					ct.Xalign = 0f;
					ct.Yalign = 0f;
					break;
				}
				case GridViewContentAlignment.TopRight : {
					ct.Xalign = 1f;
					ct.Yalign = 0f;
					break;
				}	
			}
		}
		
		void UpdateSorts (TreeViewColumn treecol)
		{
			PropertyDescriptor prop = treecolumns [treecol];
			ListSortDescription lsd = sorts.Find (l => l.PropertyDescriptor == prop);
			
			if (lsd == null) {
				lsd = new ListSortDescription (prop, ListSortDirection.Ascending);
				sorts.Add (lsd);
			} else {
				if (lsd.SortDirection == ListSortDirection.Ascending) {
					lsd.SortDirection = ListSortDirection.Descending;
				} else {
					sorts.Remove (lsd);
				}
			}
		}
		
		void UpdateHeaders ()
		{
			foreach (TreeViewColumn treecol in treecolumns.Keys) {
				PropertyDescriptor prop = treecolumns [treecol];
				GridViewColumn col = Columns.First (c => c.DataProperty == prop);
				if (col != null) {
					ListSortDescription lsd = sorts.Find (l => l.PropertyDescriptor == prop);
					if (lsd == null) {
						treecol.Title = col.HeaderText;
					} else {
						int n = sorts.IndexOf (lsd) + 1; //column order number
						treecol.Title = string.Format ("{0} {1}{2}", 
							col.HeaderText, (lsd.SortDirection == ListSortDirection.Ascending) ? "\u2193" : "\u2191", n);                               
					}
				}
			}
		}
		
		string GetSortExpression ()
		{
			if (sorts.Count == 0)
				return string.Empty;
			
			var sortexpr = new StringBuilder ();
			for (int i = 0; i < sorts.Count; i++) {
				if (i != 0) {
					sortexpr.Append (", ");
				}
				ListSortDescription lsd = sorts [i];
				sortexpr.AppendFormat ("{0} {1}", 
					lsd.PropertyDescriptor.Name, 
					(lsd.SortDirection == ListSortDirection.Ascending) ? "ASC" : "DESC");
			}
			return sortexpr.ToString ();
		}
		
		void Sort ()
		{
			if (DataSource == null)
				return;
			if (sorts == null)
				return;
			
			if (DataSource is BindingSource) {
				var bsrc = (BindingSource) DataSource;
				string sortexpr = GetSortExpression ();
				bsrc.Sort = sortexpr;
				
			} else if (DataSource is IBindingListView) {
				var listview = (IBindingListView) DataSource;
				listview.ApplySort (new ListSortDescriptionCollection (sorts.ToArray ()));
			}
		}
		
		void HandleTreeColumnClicked (object sender, EventArgs e)
		{
			var treecol = (TreeViewColumn) sender;
			
			UpdateSorts (treecol);
			UpdateHeaders ();
			RefreshDataSource ();
		}
	}
}
