//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Gtk;

namespace Gtk.Forms
{


	public interface IDecoratedBaseListWidget
	{
		TreeModel Model { get; set; }
		
		void SetActiveIter (TreeIter iter);
	}
}
