// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// This file has been generated by the GUI designer. Do not modify.


public partial class MainWindow
{
	
	private global::Gtk.Notebook notebook2;
	private global::Gtk.HBox hbox3;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::GtkForms.FormsTreeView formstreeview1;
	private global::Gtk.VButtonBox vbuttonbox1;
	private global::Gtk.Button buttonLoad;
	private global::Gtk.Label label2;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.notebook2 = new global::Gtk.Notebook ();
		this.notebook2.CanFocus = true;
		this.notebook2.Name = "notebook2";
		this.notebook2.CurrentPage = 0;
		// Container child notebook2.Gtk.Notebook+NotebookChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.formstreeview1 = new global::GtkForms.FormsTreeView ();
		this.formstreeview1.CanFocus = true;
		this.formstreeview1.Name = "formstreeview1";
		this.GtkScrolledWindow.Add (this.formstreeview1);
		this.hbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.GtkScrolledWindow]));
		w2.Position = 0;
		// Container child hbox3.Gtk.Box+BoxChild
		this.vbuttonbox1 = new global::Gtk.VButtonBox ();
		this.vbuttonbox1.Name = "vbuttonbox1";
		this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
		// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
		this.buttonLoad = new global::Gtk.Button ();
		this.buttonLoad.CanFocus = true;
		this.buttonLoad.Name = "buttonLoad";
		this.buttonLoad.UseUnderline = true;
		this.buttonLoad.Label = global::Mono.Unix.Catalog.GetString ("Load");
		this.vbuttonbox1.Add (this.buttonLoad);
		global::Gtk.ButtonBox.ButtonBoxChild w3 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.buttonLoad]));
		w3.Expand = false;
		w3.Fill = false;
		this.hbox3.Add (this.vbuttonbox1);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbuttonbox1]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		this.notebook2.Add (this.hbox3);
		// Notebook tab
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Persons");
		this.notebook2.SetTabLabel (this.hbox3, this.label2);
		this.label2.ShowAll ();
		this.Add (this.notebook2);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
