
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::GtkForms.FormsLabel label;

	private global::GtkForms.FormsEntry entry;

	private global::Gtk.HBox hbox2;

	private global::GtkForms.FormsLabel checkLabel;

	private global::GtkForms.FormsCheckButton check;

	private global::Gtk.HBox hbox3;

	private global::GtkForms.FormsLabel notifyLabel;

	private global::GtkForms.FormsEntry notifyEntry;

	private global::Gtk.HBox hbox4;

	private global::GtkForms.FormsLabel spinLabel;

	private global::GtkForms.FormsSpinButton spin;

	private global::GtkForms.FormsEntry spinEntry;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("Label entry binding demo");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.label = new global::GtkForms.FormsLabel ();
		this.label.Name = "label";
		this.hbox1.Add (this.label);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.entry = new global::GtkForms.FormsEntry ();
		this.entry.CanFocus = true;
		this.entry.Name = "entry";
		this.entry.IsEditable = true;
		this.entry.InvisibleChar = '●';
		this.hbox1.Add (this.entry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.checkLabel = new global::GtkForms.FormsLabel ();
		this.checkLabel.Name = "checkLabel";
		this.hbox2.Add (this.checkLabel);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.checkLabel]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.check = new global::GtkForms.FormsCheckButton ();
		this.check.CanFocus = true;
		this.check.Name = "check";
		this.check.DrawIndicator = true;
		this.hbox2.Add (this.check);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.check]));
		w5.Position = 1;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.notifyLabel = new global::GtkForms.FormsLabel ();
		this.notifyLabel.Name = "notifyLabel";
		this.hbox3.Add (this.notifyLabel);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.notifyLabel]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.notifyEntry = new global::GtkForms.FormsEntry ();
		this.notifyEntry.CanFocus = true;
		this.notifyEntry.Name = "notifyEntry";
		this.notifyEntry.IsEditable = true;
		this.notifyEntry.InvisibleChar = '●';
		this.hbox3.Add (this.notifyEntry);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.notifyEntry]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		this.vbox1.Add (this.hbox3);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.spinLabel = new global::GtkForms.FormsLabel ();
		this.spinLabel.Name = "spinLabel";
		this.hbox4.Add (this.spinLabel);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.spinLabel]));
		w10.Position = 0;
		w10.Expand = false;
		w10.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.spin = new global::GtkForms.FormsSpinButton ();
		this.spin.CanFocus = true;
		this.spin.Name = "spin";
		this.hbox4.Add (this.spin);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.spin]));
		w11.Position = 1;
		w11.Expand = false;
		w11.Fill = false;
		// Container child hbox4.Gtk.Box+BoxChild
		this.spinEntry = new global::GtkForms.FormsEntry ();
		this.spinEntry.CanFocus = true;
		this.spinEntry.Name = "spinEntry";
		this.spinEntry.IsEditable = true;
		this.spinEntry.InvisibleChar = '●';
		this.hbox4.Add (this.spinEntry);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.spinEntry]));
		w12.Position = 2;
		w12.Expand = false;
		w12.Fill = false;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
		w13.Position = 3;
		w13.Expand = false;
		w13.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 773;
		this.DefaultHeight = 205;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
	}
}
