// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Notebook notebook1;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Forms.FormsLabel formslabel1;
    
    private Gtk.Forms.FormsComboBox formscombobox1;
    
    private Gtk.Button button1;
    
    private Gtk.Label label1;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Forms.FormsLabel formslabel2;
    
    private Gtk.Forms.FormsComboBox formscombobox2;
    
    private Gtk.Button button2;
    
    private Gtk.Button button5;
    
    private Gtk.Label label2;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Forms.FormsLabel formslabel3;
    
    private Gtk.Forms.FormsComboBox formscombobox3;
    
    private Gtk.Button button3;
    
    private Gtk.Button button4;
    
    private Gtk.Label label3;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize(this);
        // Widget MainWindow
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("ComboBox binding");
        this.WindowPosition = ((Gtk.WindowPosition)(4));
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.notebook1 = new Gtk.Notebook();
        this.notebook1.CanFocus = true;
        this.notebook1.Name = "notebook1";
        this.notebook1.CurrentPage = 2;
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.formslabel1 = new Gtk.Forms.FormsLabel();
        this.formslabel1.Name = "formslabel1";
        this.hbox1.Add(this.formslabel1);
        Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.formslabel1]));
        w1.Position = 0;
        // Container child hbox1.Gtk.Box+BoxChild
        this.formscombobox1 = new Gtk.Forms.FormsComboBox();
        this.formscombobox1.Name = "formscombobox1";
        this.hbox1.Add(this.formscombobox1);
        Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.formscombobox1]));
        w2.Position = 1;
        w2.Expand = false;
        w2.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.button1 = new Gtk.Button();
        this.button1.Sensitive = false;
        this.button1.CanFocus = true;
        this.button1.Name = "button1";
        this.button1.UseUnderline = true;
        this.button1.Label = Mono.Unix.Catalog.GetString("GtkButton");
        this.hbox1.Add(this.button1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.button1]));
        w3.Position = 2;
        w3.Expand = false;
        w3.Fill = false;
        this.notebook1.Add(this.hbox1);
        // Notebook tab
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("List");
        this.notebook1.SetTabLabel(this.hbox1, this.label1);
        this.label1.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.formslabel2 = new Gtk.Forms.FormsLabel();
        this.formslabel2.Name = "formslabel2";
        this.hbox2.Add(this.formslabel2);
        Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.formslabel2]));
        w5.Position = 0;
        // Container child hbox2.Gtk.Box+BoxChild
        this.formscombobox2 = new Gtk.Forms.FormsComboBox();
        this.formscombobox2.Name = "formscombobox2";
        this.hbox2.Add(this.formscombobox2);
        Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.formscombobox2]));
        w6.Position = 1;
        w6.Expand = false;
        w6.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.button2 = new Gtk.Button();
        this.button2.CanFocus = true;
        this.button2.Name = "button2";
        this.button2.UseUnderline = true;
        this.button2.Label = Mono.Unix.Catalog.GetString("Change first item");
        this.hbox2.Add(this.button2);
        Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.button2]));
        w7.Position = 2;
        w7.Expand = false;
        w7.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.button5 = new Gtk.Button();
        this.button5.CanFocus = true;
        this.button5.Name = "button5";
        this.button5.UseUnderline = true;
        this.button5.Label = Mono.Unix.Catalog.GetString("Set position");
        this.hbox2.Add(this.button5);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox2[this.button5]));
        w8.Position = 3;
        w8.Expand = false;
        w8.Fill = false;
        this.notebook1.Add(this.hbox2);
        Gtk.Notebook.NotebookChild w9 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox2]));
        w9.Position = 1;
        // Notebook tab
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("BindingSource");
        this.notebook1.SetTabLabel(this.hbox2, this.label2);
        this.label2.ShowAll();
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.formslabel3 = new Gtk.Forms.FormsLabel();
        this.formslabel3.Name = "formslabel3";
        this.hbox3.Add(this.formslabel3);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox3[this.formslabel3]));
        w10.Position = 0;
        // Container child hbox3.Gtk.Box+BoxChild
        this.formscombobox3 = new Gtk.Forms.FormsComboBox();
        this.formscombobox3.Name = "formscombobox3";
        this.hbox3.Add(this.formscombobox3);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox3[this.formscombobox3]));
        w11.Position = 1;
        w11.Expand = false;
        w11.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.button3 = new Gtk.Button();
        this.button3.CanFocus = true;
        this.button3.Name = "button3";
        this.button3.UseUnderline = true;
        this.button3.Label = Mono.Unix.Catalog.GetString("Change first item");
        this.hbox3.Add(this.button3);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox3[this.button3]));
        w12.Position = 2;
        w12.Expand = false;
        w12.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.button4 = new Gtk.Button();
        this.button4.CanFocus = true;
        this.button4.Name = "button4";
        this.button4.UseUnderline = true;
        this.button4.Label = Mono.Unix.Catalog.GetString("Clear");
        this.hbox3.Add(this.button4);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.hbox3[this.button4]));
        w13.Position = 3;
        w13.Expand = false;
        w13.Fill = false;
        this.notebook1.Add(this.hbox3);
        Gtk.Notebook.NotebookChild w14 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.hbox3]));
        w14.Position = 2;
        // Notebook tab
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("BindingList");
        this.notebook1.SetTabLabel(this.hbox3, this.label3);
        this.label3.ShowAll();
        this.Add(this.notebook1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 345;
        this.DefaultHeight = 77;
        this.button1.Hide();
        this.Show();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.button1.Clicked += new System.EventHandler(this.OnButton1Clicked);
        this.button2.Clicked += new System.EventHandler(this.OnButton2Clicked);
        this.button5.Clicked += new System.EventHandler(this.OnButton5Clicked);
        this.button3.Clicked += new System.EventHandler(this.OnButton3Clicked);
        this.button4.Clicked += new System.EventHandler(this.OnButton4Clicked);
    }
}
