// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// This file has been generated by the GUI designer. Do not modify.
namespace GtkForms.Custom
{
	public partial class DatePicker
	{
		
		private global::Gtk.HBox hbox;
		private global::Gtk.Entry entry;
		private global::Gtk.Button button;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkForms.Custom.DatePicker
			global::Stetic.BinContainer.Attach (this);
			this.Name = "GtkForms.Custom.DatePicker";
			// Container child GtkForms.Custom.DatePicker.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			// Container child hbox.Gtk.Box+BoxChild
			this.entry = new global::Gtk.Entry ();
			this.entry.CanFocus = true;
			this.entry.Name = "entry";
			this.entry.IsEditable = true;
			this.entry.InvisibleChar = '●';
			this.hbox.Add (this.entry);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox [this.entry]));
			w1.Position = 0;
			// Container child hbox.Gtk.Box+BoxChild
			this.button = new global::Gtk.Button ();
			this.button.HeightRequest = 0;
			this.button.CanFocus = true;
			this.button.Name = "button";
			this.button.Relief = ((global::Gtk.ReliefStyle)(2));
			this.button.Xalign = 0F;
			this.button.Yalign = 0F;
			// Container child button.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0F, 0F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("calendar_22x16.png");
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w3.Add (w6);
			w2.Add (w3);
			this.button.Add (w2);
			this.hbox.Add (this.button);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox [this.button]));
			w10.Position = 1;
			w10.Expand = false;
			this.Add (this.hbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
