// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// This file has been generated by the GUI designer. Do not modify.
namespace DatePickerDemo
{


	public partial class MainWindow
	{

		private global::Gtk.HBox hbox;

		private global::GtkForms.FormsLabel label;

		private global::GtkForms.FormsDatePicker datepicker;

		private global::GtkForms.FormsLabel label2;

		private global::GtkForms.FormsDatePicker datepicker2;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget DatePickerDemo.MainWindow
			this.Name = "DatePickerDemo.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("DatePicker demo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child DatePickerDemo.MainWindow.Gtk.Container+ContainerChild
			this.hbox = new global::Gtk.HBox ();
			this.hbox.Name = "hbox";
			this.hbox.Spacing = 6;
			// Container child hbox.Gtk.Box+BoxChild
			this.label = new global::GtkForms.FormsLabel ();
			this.label.Name = "label";
			this.label.LabelProp = global::Mono.Unix.Catalog.GetString ("formslabel1");
			this.label.FontSize = 10;
			this.hbox.Add (this.label);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox[this.label]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.datepicker = new global::GtkForms.FormsDatePicker ();
			this.hbox.Add (this.datepicker);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox[this.datepicker]));
			w2.Position = 1;
			// Container child hbox.Gtk.Box+BoxChild
			this.label2 = new global::GtkForms.FormsLabel ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("formslabel1");
			this.label2.FontSize = 10;
			this.hbox.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox[this.label2]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox.Gtk.Box+BoxChild
			this.datepicker2 = new global::GtkForms.FormsDatePicker ();
			this.hbox.Add (this.datepicker2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox[this.datepicker2]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.Add (this.hbox);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 572;
			this.DefaultHeight = 64;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		}
	}
}
