// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// This file has been generated by the GUI designer. Do not modify.
namespace GtkForms.Custom
{


	public partial class CalendarWindow
	{

		private global::Gtk.Calendar calendar;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget GtkForms.Custom.CalendarWindow
			this.Name = "GtkForms.Custom.CalendarWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("CalendarWindow");
			this.TypeHint = ((global::Gdk.WindowTypeHint)(3));
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			this.SkipTaskbarHint = true;
			// Container child GtkForms.Custom.CalendarWindow.Gtk.Container+ContainerChild
			this.calendar = new global::Gtk.Calendar ();
			this.calendar.CanFocus = true;
			this.calendar.Name = "calendar";
			this.calendar.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.Add (this.calendar);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 237;
			this.DefaultHeight = 216;
			this.Show ();
			this.calendar.DaySelectedDoubleClick += new global::System.EventHandler (this.Calendar_DaySelectedDoubleClick);
		}
	}
}
